package kr.dwas.dwas_EQ.device

enum class SocFamily(val label: String) { MEDIA_TEK("MediaTek"), QUALCOMM("Qualcomm"), UNKNOWN("Unknown") }

data class DeviceCompatibilityInfo(
    val model: String,
    val lgsiProject: String,
    val androidVersion: Int,
    val platform: String,
    val hardware: String,
    val daxGeneration: Int?,
    val tuningCaptured: Boolean,
    val spatializerEvidence: Boolean = false,
    val fullSessionStandardFx: Boolean = false,
    val noDynamicsProcessingStandardFx: Boolean = false,
    val note: String,
    val nativeFxVerified: Boolean = false,
    val speakerSafeFourFx: Boolean = false,
    val aliases: Set<String> = emptySet(),
    val dolbyGeqRuntimeInactive: Boolean = false,
    val publicBassBoostRuntimeInactive: Boolean = false,
    val publicVirtualizerRuntimeInactive: Boolean = false,
    val isolatedSessionStrengthFx: Boolean = false,
) {
    val socFamily: SocFamily get() = when {
        hardware.startsWith("mt", ignoreCase = true) -> SocFamily.MEDIA_TEK
        hardware.equals("qcom", ignoreCase = true) || platform.startsWith("sm", ignoreCase = true) -> SocFamily.QUALCOMM
        else -> SocFamily.UNKNOWN
    }
    val capabilityOnly: Boolean get() = !tuningCaptured
}

object DeviceCompatibilityDatabase {
    val models = listOf(
        DeviceCompatibilityInfo("TB320FC", "asphalt", 15, "taro", "qcom", 15, true, fullSessionStandardFx = false, note = "Android 15 Qualcomm taro DAX 15; captured hardware reports TB320FC and TB320FU is an archive-label identity alias. The captured session-0 Dolby DAP, primary output and deep-buffer speaker output are stereo 0x3. AudioFlinger exposes QTI/NXP proxy BassBoost and Virtualizer together with direct software DynamicsProcessing. Equalizer, Headroom, Limiter, Channel Balance, Bass Boost and Virtualizer are validated on real hardware with the global stereo Standard FX baseline and the dwas_EQ DynamicsProcessing bypass for unsafe QTI/NXP proxies. Android Spatializer reports not supported.", nativeFxVerified = true, aliases = setOf("TB320FU")),
        DeviceCompatibilityInfo("TB322FC", "elden", 16, "sun", "qcom", 16, true, fullSessionStandardFx = false, note = "Android 16 Qualcomm sun elden DAX 16; the captured session-0 Dolby DAP and output mixers are stereo 0x3 and the direct software Standard FX baseline is validated on real hardware for Equalizer, Headroom, Limiter, Channel Balance, Bass Boost and Virtualizer. Preset Reverb remains experimental.", nativeFxVerified = true),
        DeviceCompatibilityInfo("TB323FU", "baldur", 16, "canoe", "qcom", 16, true, fullSessionStandardFx = false, note = "Android 16 Qualcomm canoe baldur DAX 16; the captured session-0 Dolby DAP and all output mixers are stereo 0x3. system_audio_effects.xml is identical to the TB322FC capture and exposes direct software BassBoost, Virtualizer and DynamicsProcessing. Equalizer, Headroom, Limiter, Channel Balance, Bass Boost and Virtualizer are validated on real hardware with the existing global stereo Standard FX baseline and Device Dolby GEQ AUTO path. Android Spatializer is not active and Preset Reverb remains experimental.", nativeFxVerified = true),
        DeviceCompatibilityInfo("TB331FC", "", 13, "bengal", "qcom", 13, true, spatializerEvidence = true, note = "Android 13 reference capture; DAX 13, session-0 DAP, 20-slot dax-default tuning and vendor spatializer registration captured."),
        DeviceCompatibilityInfo("TB335FC", "sycamore", 16, "mt6835", "mt8755", 16, true, spatializerEvidence = false, fullSessionStandardFx = false, noDynamicsProcessingStandardFx = false, note = "Android 16 MediaTek mt6835/mt8755 sycamore DAX 16; Device Dolby GEQ, Headroom, Limiter and Channel Balance are validated on real hardware. The public global direct software BassBoost and Virtualizer implementations create, accept parameters and enable successfully but produce no audible speaker change across repeated 0..1000 strength sweeps, so only those two false-positive public routes are bypassed through the existing dwas_EQ global DynamicsProcessing path. Build Fix 55 Bass Boost and Virtualizer fallback is validated on real hardware; the final capture repeatedly creates Dynamics Processing on session 0, installs it in the AudioFlinger effect chain and selects it as the session-0 volume controller while Dolby DAP continues processing stereo 0x3. Dolby Spatializer is registered in vendor configuration but the captured runtime reports Spatializer unsupported with no active Spatializer effect. Preset Reverb remains experimental.", nativeFxVerified = true, speakerSafeFourFx = false, publicBassBoostRuntimeInactive = true, publicVirtualizerRuntimeInactive = true),
        DeviceCompatibilityInfo("TB336FU", "sycamore", 16, "mt6835", "mt8755", 16, true, spatializerEvidence = false, fullSessionStandardFx = false, noDynamicsProcessingStandardFx = false, note = "Android 16 MediaTek mt6835/mt8755 sycamore DAX 16 real-device capture. The captured system_audio_effects.xml and vendor_audio_effects.xml are byte-identical to the TB335FC capture, speaker outputs and Dolby DAP processing are stereo 0x3, and direct software BassBoost, Virtualizer and DynamicsProcessing are exposed. Equalizer, Headroom, Limiter and Channel Balance are confirmed working on real hardware. Public global BassBoost and Virtualizer create successfully, accept parameters and enable on session 0 but produce no audible change across 0..1000 strength sweeps, matching the TB335FC functional false-positive pattern, so only those two routes are bypassed through the existing dwas_EQ global DynamicsProcessing path. Build Fix 57 Bass Boost and Virtualizer fallback is validated on real hardware; the final validation log repeatedly creates Dynamics Processing on session 0 and selects it as the session-0 volume controller while public Dynamic Bass Boost and Virtualizer are absent from the final effect creation path. The supplied environment is described as global ROM and UDS reports TB336FU_ROW while the captured build fingerprint contains a TB336FU_PRC product label; audio routing therefore follows measured topology rather than ROM label. Dolby Spatializer is registered but the captured audio policy reports Spatializer unsupported. Preset Reverb remains experimental.", nativeFxVerified = true, speakerSafeFourFx = false, publicBassBoostRuntimeInactive = true, publicVirtualizerRuntimeInactive = true),
        DeviceCompatibilityInfo("TB361FU", "cava", 15, "mt6835", "mt8755", 15, true, spatializerEvidence = false, fullSessionStandardFx = false, noDynamicsProcessingStandardFx = false, note = "Android 15 MediaTek mt6835/mt8755 cava DAX 15 global-ROM capture. Real device properties identify TB361FU even though the collector SelectedModel field contains TB375FC. The captured system_audio_effects.xml and vendor_audio_effects.xml are byte-identical to the validated TB365FC capture and expose direct software BassBoost, Virtualizer and DynamicsProcessing. The captured speaker output and Dolby DAP path are stereo 0x3 on session 0, Dolby DAP continues active processing and the user confirms Equalizer is audible. The real-device log shows public global Dynamic Bass Boost and Virtualizer repeatedly create successfully on session 0 with the standard AOSP UUIDs and successful AudioEffect setup but produce no audible change, while global DynamicsProcessing creates on session 0 and is selected by AudioFlinger as the volume controller. Build Fix 65 therefore bypasses only the two runtime-inactive public strength effects through the existing dwas_EQ global DynamicsProcessing path. Headroom, Limiter, Channel Balance, Equalizer, Dolby backend order, route safety, persistence and Build Fix 64 session recovery remain unchanged. The supplied device is identified by the user as global ROM while TB365FC is China domestic ROM, so the strength-effect quirk follows measured audio topology and runtime behavior rather than ROM label. Native strength fallback remains pending TB361FU real-device revalidation and Preset Reverb remains experimental.", nativeFxVerified = false, speakerSafeFourFx = false, publicBassBoostRuntimeInactive = true, publicVirtualizerRuntimeInactive = true),
        DeviceCompatibilityInfo("TB365FC", "cava", 16, "mt6835", "mt8755", 16, true, spatializerEvidence = false, fullSessionStandardFx = false, noDynamicsProcessingStandardFx = false, note = "Android 16 MediaTek mt6835/mt8755 cava DAX 16 PRC capture. The real device properties identify TB365FC even though the collector SelectedModel field contains TB335FC. Captured system_audio_effects.xml and vendor_audio_effects.xml are byte-identical to the validated TB336FU capture, the active speaker and Dolby DAP path are stereo 0x3 on session 0, and direct software BassBoost, Virtualizer and DynamicsProcessing are exposed. Build Fix 61 Bass Boost and Virtualizer fallback is validated on real hardware together with Equalizer, Headroom, Limiter and Channel Balance. The final validation log uses session-0 dwas_EQ DynamicsProcessing for the strength effects, repeatedly selects it as the AudioFlinger volume controller, continues successful Dolby DAP 20-gain reads, and contains no dwas_EQ fatal exception or Dolby route block. The existing dwas_EQ global DynamicsProcessing fallback remains the verified TB365FC Bass Boost and Virtualizer route; Equalizer, Headroom, Limiter, Channel Balance, Dolby backend order, route safety and persistence remain unchanged. TB361FU is maintained as a separately captured Android 15 global-ROM profile rather than an alias because its Android and DAX generations differ. Preset Reverb remains experimental.", nativeFxVerified = true, speakerSafeFourFx = false, publicBassBoostRuntimeInactive = true, publicVirtualizerRuntimeInactive = true),
        DeviceCompatibilityInfo("TB373FU", "peridot", 16, "mt6897", "mt8792", 16, true, fullSessionStandardFx = true, noDynamicsProcessingStandardFx = true, note = "Android 16 MediaTek mt6897/mt8792 peridot DAX 16 global-ROM capture. Bass Boost and Virtualizer remain real-device functional through the existing speaker-safe routing, and AUTO Equalizer continues to use the Android Equalizer playback-session fallback because the Device Dolby GEQ path is runtime-inactive. The pre-fix real-device log proves the playback-session DynamicsProcessing core path is unsafe: 10 captured DynamicsProcessing creations produced 40 null DynamicsProcessing reset events and 10 EFFECT_CMD_SET_VOLUME invalid channel 0 events while the user reported audible breakup when Headroom, Limiter or Channel Balance activated. Build Fix 82 applies the generic knownNoDynamicsProcessingQuirk fail-closed policy to those core controls. Build Fix 83 validates that policy against the follow-up real-device log: 0 DynamicsProcessing creations, 0 invalid-channel events and 0 null DynamicsProcessing events are observed while 10 Equalizer creations and 6 Virtualizer creations remain present. The route-level regression is therefore validated without model-name routing; audible result still requires human listening confirmation. Bass Boost, Virtualizer, Android Equalizer, Dolby backend order and Preset Reverb experimental status remain unchanged.", speakerSafeFourFx = true, dolbyGeqRuntimeInactive = true),
        DeviceCompatibilityInfo("TB375FC", "peridot", 16, "mt6897", "mt8792", 16, true, fullSessionStandardFx = true, noDynamicsProcessingStandardFx = true, note = "Android 16 MediaTek mt6897/mt8792 peridot DAX 16 PRC capture. The captured system_audio_effects.xml and vendor_audio_effects.xml are byte-identical to the TB373FU peridot capture. Bass Boost, Virtualizer and the Android Equalizer playback-session fallback remain validated on real hardware through the existing speaker-safe routes because the Device Dolby GEQ path is runtime-inactive. Build Fix 82 applies the same generic knownNoDynamicsProcessingQuirk fail-closed policy to Headroom, Limiter and Channel Balance because the shared peridot audio topology now has direct TB373FU evidence of null DynamicsProcessing reset state, invalid channel volume control and audible breakup. This precaution follows measured topology rather than ROM label or model-name hardcoding and can be lifted only after independent real-device evidence proves a safe DynamicsProcessing core path. Build Fix 84 also exposes this fail-closed state in the UI so Headroom, Limiter and Channel Balance remain visibly disabled on both TB373FU and TB375FC while safe Equalizer, Bass Boost and Virtualizer routes remain available. Preset Reverb remains experimental.", speakerSafeFourFx = true, dolbyGeqRuntimeInactive = true),
        DeviceCompatibilityInfo("TB376FC", "malbec", 16, "sun", "qcom", 16, true, fullSessionStandardFx = true, note = "Qualcomm sun malbec; playback-session Standard FX is validated on real hardware and avoids the unsafe global four-channel speaker boundary."),
        DeviceCompatibilityInfo("TB378FC", "zhiyu", 16, "sun", "qcom", 16, true, spatializerEvidence = true, fullSessionStandardFx = true, note = "Qualcomm sun zhiyu; playback-session Standard FX is validated on real hardware with stereo 0x3 DynamicsProcessing and avoids the separate four-channel 0x33 speaker boundary."),
        DeviceCompatibilityInfo("TB371FC", "lgsi", 14, "kona", "qcom", 14, true, fullSessionStandardFx = true, isolatedSessionStrengthFx = true, note = "Android 14 Qualcomm kona lgsi DAX 14 PRC capture. Real-device Build Fix 88 evidence supersedes the three previous TB371FC strength candidates. The captured QTI proxy BassBoost and Virtualizer route caused perceived volume-control and strength-retention failures, while direct creation of the nested software BassBoost and Virtualizer UUIDs fails in EffectFactoryHAL with descriptor ENOENT and AudioEffect initialization status -3. Headroom, Limiter and Channel Balance remain on the existing playback-session DynamicsProcessing core because the user confirms those controls remain audible. AUTO Equalizer uses the existing Android Equalizer playback-session fallback because Device Dolby DAP parameter updates are observed but the user confirms the requested EQ curve is not audible and DAX repeatedly resolves its own detailed IEQ state. Bass Boost uses the existing dwas_EQ Android Equalizer bass overlay so it does not instantiate the failed QTI proxy or nested software BassBoost effect. Virtualizer is fail-closed on this verified topology instead of exposing a control that cannot retain an audible effect safely. Explicit non-AUTO backend selections remain available, and backend ordering, Safe Probe, rollback, persistence and Preset Reverb experimental routing are unchanged.", dolbyGeqRuntimeInactive = true),
        DeviceCompatibilityInfo("TB390FU", "malbec", 16, "sun", "qcom", 16, true, fullSessionStandardFx = true, note = "Qualcomm sun; full Standard FX prefers active playback sessions because global-mix processing is unstable on the captured device."),
        DeviceCompatibilityInfo("TB520FU", "lapis", 16, "pineapple", "qcom", 16, true, fullSessionStandardFx = false, note = "Qualcomm pineapple lapis; the captured stereo 0x3 global Standard FX path and the dwas_EQ DynamicsProcessing bypass for unsafe QTI BassBoost and Virtualizer proxies are validated on real hardware together with Equalizer, Headroom, Limiter and Channel Balance; Android Spatializer reports unsupported.", nativeFxVerified = true),
        DeviceCompatibilityInfo("TB522FU", "mojito", 16, "sun", "qcom", 16, false, note = "Minimal collector only; dax-default.xml not captured. Runtime capability detection only.", nativeFxVerified = true),
        DeviceCompatibilityInfo("TB710FU", "topaz", 16, "pineapple", "qcom", 16, true, spatializerEvidence = true, fullSessionStandardFx = false, note = "Qualcomm pineapple topaz; the captured primary output and session-0 Dolby DAP are stereo 0x3, matching the TB520FU global baseline. Equalizer, Headroom, Limiter, Channel Balance, Bass Boost and Virtualizer are validated on real hardware with the global Standard FX baseline and QTI proxy-aware dwas_EQ DynamicsProcessing bypass. The successful log also confirms native Dolby GEQ band commits while Android Spatializer capability remains evidence-only because the captured Spatializer is disabled with no active effect handle.", nativeFxVerified = true),
    )

    fun find(model: String?): DeviceCompatibilityInfo? = models.firstOrNull { info ->
        info.model.equals(model, ignoreCase = true) || info.aliases.any { it.equals(model, ignoreCase = true) }
    }

    fun findByIdentity(
        model: String?,
        device: String?,
        product: String?,
        fingerprint: String?,
    ): DeviceCompatibilityInfo? {
        val direct = listOf(model, device, product)
            .filterNotNull()
            .firstNotNullOfOrNull(::find)
        if (direct != null) return direct
        val rawFingerprint = fingerprint.orEmpty()
        return models.firstOrNull { info ->
            rawFingerprint.contains("/${info.model}/", ignoreCase = true) ||
                rawFingerprint.contains("/${info.model}:", ignoreCase = true)
        }
    }
}
